CREATE TABLE IF NOT EXISTS inspect_record (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    plan_id     BIGINT       NOT NULL COMMENT '关联巡检计划',
    plan_project_id BIGINT   NOT NULL COMMENT '关联巡检计划项目',
    project_id  BIGINT       NOT NULL COMMENT '关联项目',
    station_id  BIGINT       NOT NULL COMMENT '关联电站',
    inspector_id BIGINT      NOT NULL COMMENT '巡检人员',
    weather     VARCHAR(50)   NULL    COMMENT '天气情况',
    device_name VARCHAR(50)  NULL    COMMENT '检测设备名称',
    device_model VARCHAR(50) NULL    COMMENT '检测设备型号',
    watermark_config JSON DEFAULT NULL COMMENT '水印配置',
    checklist_result JSON    NULL     COMMENT '巡检结果',
    photos      JSON         NULL     COMMENT '照片URL(按section分组)',
    longitude   DECIMAL(12,6) NULL    COMMENT '经度',
    latitude    DECIMAL(12,6) NULL    COMMENT '纬度',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '1=已提交 2=已驳回',
    reject_reason VARCHAR(300) DEFAULT NULL COMMENT '驳回原因',
    edit_deadline datetime DEFAULT NULL COMMENT '开放编辑截止时间',
    pdf_status TINYINT NOT NULL DEFAULT 0 COMMENT '0=未生成 1=生成中 2=成功 3=失败',
    pdf_retry INT NOT NULL DEFAULT 0 COMMENT 'PDF生成重试次数',
    pdf_url     VARCHAR(100)  NULL    COMMENT '报告PDF文件地址',
    create_time DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    version INT NOT NULL DEFAULT 1 COMMENT '乐观锁版本号',
    INDEX idx_station_id (station_id),
    INDEX idx_inspector_id (inspector_id),
    INDEX idx_project_id (project_id),
    INDEX idx_status (status,pdf_status),
    INDEX idx_plan_project_status (plan_id,project_id,status),
    INDEX idx_plan_station_status (plan_project_id,status,station_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检记录';
