CREATE TABLE `inverter` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT NOT NULL COMMENT '所属项目ID',
  `inverter_code` VARCHAR(50) NOT NULL COMMENT '逆变器编号',
  `owner_name` VARCHAR(30) NOT NULL COMMENT '户主姓名',
  `address` VARCHAR(255) DEFAULT NULL COMMENT '装机地址',
  `power_account` VARCHAR(50) DEFAULT NULL COMMENT '发电户号',
  `inverter_sn` VARCHAR(50) DEFAULT NULL COMMENT '逆变器序列号',
  `inverter_brand` VARCHAR(50) DEFAULT NULL COMMENT '逆变器品牌型号',
  `module_spec` VARCHAR(100) DEFAULT NULL COMMENT '组件规格型号',
  `module_count` INT DEFAULT NULL COMMENT '组件块数',
  `capacity_kw` DECIMAL(10,2) DEFAULT NULL COMMENT '装机容量(kW)',
  `longitude` DECIMAL(12,8) DEFAULT NULL COMMENT '经度坐标',
  `latitude` DECIMAL(12,8) DEFAULT NULL COMMENT '纬度坐标',
  `status` TINYINT NOT NULL DEFAULT 0 COMMENT '巡检状态: 0-未巡检 1-已巡检',
  `last_inspector_id` BIGINT DEFAULT NULL COMMENT '最后巡检人ID',
  `last_inspect_time` DATETIME DEFAULT NULL COMMENT '最后巡检时间',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_inverter_code` (`inverter_code`),
  KEY `idx_project_id` (`project_id`),
  KEY `idx_owner_name` (`owner_name`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='逆变器表';
